management:
  endpoint: # ??? ????? enabled ??
    health:
      show-details: always
  #    beans:
#      enabled: false
#    caches:
#      enabled: true
#    heapdump:
#      enabled: true
  endpoints: # ??? ??? ??
    web:
      cors:
        allowed-origins: http://test.com
        allowed-methods: GET, POST
      exposure:
        include: "*"
#        exclude:
#          - beans
  info:
    env:
      enabled: true
    git:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
