management:
  endpoint: # ??? ????? enabled ??
    health:
      show-details: always
  #    beans:
#      enabled: false
#    caches:
#      enabled: true
#    heapdump:
#      enabled: true
  endpoints: # ??? ??? ??
    web:
      cors:
        allowed-origins: http://test.com
        allowed-methods: GET, POST
      exposure:
        include: "*"
#        exclude:
#          - beans
